# Generated by Django 4.1.7 on 2023-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publised_countries',
            field=models.ManyToManyField(related_name='countries', to='book_outlet.country'),
        ),
    ]
